/**
 * The AWS target's configuration surface.
 *
 * The Helm chart configures a deployment through `values.yaml`; this target uses a
 * `.env` file instead, because the repo already has that surface (`.env`,
 * `.env.example`, `.env.test`, `.env.demo`) and `@grantjs/env` already defines every
 * key. A second format would mean two places to learn and two to drift.
 *
 * Layering, outermost last:
 *
 *   AWS_TARGET_ENV_DEFAULTS  →  the .env file  →  values the stack computes itself
 *
 * The defaults are not replaced by this file: a key the file omits keeps its default.
 *
 * **Secrets do not travel this path.** CloudFormation cannot place a literal secret
 * into a resource without that literal appearing in the template, so keys the
 * application resolves through `ISecretResolver` are split out here and never handed
 * to the stack. They are written to the platform secret out of band instead — which
 * is also the property ADR 0004 bought: a rotation is picked up within the resolver's
 * TTL rather than at the next redeploy.
 */

import type { GrantEnv } from './props';

/**
 * Keys the application reads through `ISecretResolver` rather than `process.env`,
 * and which an operator supplies. Derived from the call sites, not convention:
 * `services/github-oauth.service.ts` and `services/user-mfa.service.ts`.
 *
 * `DB_URL` is resolver-backed too but is not here, and it is not settable from this
 * file at all — see `STACK_COMPOSED_KEYS`.
 */
/**
 * The shape of a key anything will actually read: upper-case, as `@grantjs/env`
 * declares them and as `process.env` matches them.
 *
 * Exported because `validate.ts` applies the identical rule to `GrantPlatformProps.env`,
 * which has no parser in front of it.
 */
export const ENV_KEY_SHAPE = /^[A-Z_][A-Z0-9_]*$/;

export const RESOLVER_SECRET_KEYS = [
  'GITHUB_CLIENT_SECRET',
  'AUTH_MFA_SECRET_ENCRYPTION_KEY',

  // Routed rather than refused since `apps/api/src/config/credentials.ts` began
  // overlaying resolver-provided values onto `config` in the composition root, before
  // the first adapter is built. Thirteen keys, in the same order as the table there so
  // the two lists can be diffed by eye — that file is the other half of this one, and a
  // key present here but absent there would be written to the platform secret and read
  // by nothing.
  'CACHE_DYNAMODB_ACCESS_KEY_ID',
  'CACHE_DYNAMODB_SECRET_ACCESS_KEY',
  'REDIS_PASSWORD',
  'SECURITY_API_KEY',
  'MAILGUN_API_KEY',
  'MAILJET_API_KEY',
  'MAILJET_SECRET_KEY',
  'EMAIL_SES_CLIENT_SECRET',
  'SMTP_PASSWORD',
  'STORAGE_S3_ACCESS_KEY_ID',
  'STORAGE_S3_SECRET_ACCESS_KEY',
  'JOBS_AWS_ACCESS_KEY_ID',
  'JOBS_AWS_SECRET_ACCESS_KEY',
] as const;

/**
 * Composed by the stack rather than read from this file, and refused if set here.
 *
 * `DB_URL` carries a password, so the two paths this file offers are both wrong for
 * it. As ordinary `env` it becomes a Lambda environment variable — plaintext in the
 * CloudFormation template and in the function configuration, which is the hazard
 * `CREDENTIAL_KEYS` exists to name. As a `RESOLVER_SECRET_KEYS` entry it would be
 * written out of band by `put-secrets`, which reads the deployed stack's outputs and
 * therefore cannot run until the deploy has already finished — leaving the migration
 * and the API's first minutes with no database URL at all.
 *
 * So it is supplied through the construct library instead, where a `SecretValue` can
 * render a `{{resolve:secretsmanager:…}}` reference that CloudFormation resolves at
 * deploy time: present when the stack comes up, absent from the template.
 */
export const STACK_COMPOSED_KEYS = ['DB_URL'] as const;

/**
 * Generated by the stack and trusted by CloudFront. Supplying it from a file would
 * both put a live secret in the template and break the origin check if it disagreed
 * with what the distribution sends, so it is refused rather than silently ignored.
 */
export const STACK_GENERATED_KEYS = ['ORIGIN_VERIFY_SECRET'] as const;

/**
 * Credentials with **no safe path on this target**, refused rather than routed.
 *
 * Everything not in `RESOLVER_SECRET_KEYS` becomes a Lambda environment variable,
 * which is a literal string in the CloudFormation template and in the function
 * configuration — readable by anyone holding `cloudformation:GetTemplate` or
 * `lambda:GetFunctionConfiguration`, and written to `cdk.out` on disk. Lambda has no
 * equivalent of the ECS task's `Secrets`/`ValueFrom`, where the agent fetches the
 * value at start and the template carries only an ARN. That asymmetry is why
 * `ISecretResolver` exists (ADR 0004).
 *
 * **This list used to hold seventeen keys, and the reason it gave for thirteen of them
 * was wrong.** It said the adapters read those keys from `process.env`, so a value in
 * the platform secret would be hidden from the application too — and that routing them
 * meant work "across the email, cache, storage and jobs packages". None of it was true:
 * `grep -rn 'process\.env' packages/@grantjs/{email,cache,storage,jobs}/src` returns
 * nothing. Every one of those keys lands in `apps/api/src/config/env.config.ts` and is
 * handed to an adapter as ordinary constructor config, so overlaying resolved values in
 * the composition root was one file plus a call — `apps/api/src/config/credentials.ts`.
 * They are in `RESOLVER_SECRET_KEYS` now.
 *
 * What remains is four keys, and each is a separate decision rather than a leftover:
 *
 *   - `DB_GRANT_ROLE_URL` — a **superuser** connection string, and the most valuable
 *     credential in this file. `@grantjs/database`'s `grant-rls-login-role.lib.ts:10`
 *     reads it from `process.env` during a migration, outside any composition root, so
 *     the overlay cannot reach it. Routing it means changing the RLS grant path's
 *     shape, which is its own story.
 *   - `POSTGRES_PASSWORD` — refused here because it **already has a route**, not
 *     because it lacks one. `@grantjs/env` composes `DB_URL` from the discrete
 *     `POSTGRES_*` parts, and `DB_URL` is resolver-backed
 *     (`apps/api/src/lib/secrets/database-url.ts`) and supplied through
 *     `STACK_COMPOSED_KEYS`. Setting this one here would put a password in the
 *     template to build a URL that arrives by a safe path anyway.
 *   - `E2E_DB_URL`, `E2E_REDIS_PASSWORD` — **test-harness keys with no production
 *     caller.** Nothing in `apps/api` reads either outside `tests/`. Giving them a
 *     production secret store would be inventing a use for them.
 *
 * The honest answer for all four is still refusal at synth with a sentence saying why,
 * in preference to a credential that deploys successfully and leaks quietly. Gate 4,
 * finding F-C.
 */
export const CREDENTIAL_KEYS = [
  // Two connection strings that carry a password inside a URL, so `CREDENTIAL_SHAPED`
  // in credential-keys.test.ts cannot see them either — the same blind spot DB_URL
  // has, without DB_URL's alternative.
  'DB_GRANT_ROLE_URL',
  'E2E_DB_URL',
  'E2E_REDIS_PASSWORD',
  'POSTGRES_PASSWORD',
] as const;

export interface TargetConfig {
  /** Non-secret keys, destined for the container environment. */
  readonly env: GrantEnv;
  /** Resolver-backed keys, destined for the platform secret out of band. */
  readonly secrets: Readonly<Record<string, string>>;
}

/**
 * Minimal `.env` parser: `KEY=value`, `#` comments, optional `export`, and quoted
 * values. Deliberately not `dotenv` — this reads a file at synth time to build a
 * template, and a parser small enough to read is worth more here than one that also
 * mutates `process.env`.
 */
export function parseEnvFile(contents: string): Record<string, string> {
  const result: Record<string, string> = {};

  for (const rawLine of contents.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) {
      continue;
    }

    const withoutExport = line.startsWith('export ') ? line.slice('export '.length) : line;
    const eq = withoutExport.indexOf('=');
    if (eq <= 0) {
      continue;
    }

    const key = withoutExport.slice(0, eq).trim();

    // Upper-case only, and a lower-case key is refused rather than skipped.
    //
    // This regex used to carry an `i` flag while every refusal below matches the key
    // exactly, so `db_url=` or `smtp_password=` slipped past all three key lists and
    // was synthesized into the template as a Lambda environment variable. The
    // application never reads it — `@grantjs/env` declares no lower-case key and
    // `process.env` is case-sensitive — so the value had no effect whatsoever except
    // to place a credential in the CloudFormation template, in the function
    // configuration and in `cdk.out` on disk. A silent skip would close the leak and
    // leave the operator believing the key was set, so it is an error instead.
    if (!ENV_KEY_SHAPE.test(key)) {
      if (/^[A-Za-z_][A-Za-z0-9_]*$/.test(key)) {
        throw new Error(
          `${key}: environment keys are upper-case. @grantjs/env declares none in ` +
            'this form, so this line would be read by nothing — while its value would ' +
            'still be synthesized into the template as a Lambda environment variable, ' +
            'in plaintext, past every refusal in this file. Rename it or remove it.'
        );
      }
      continue;
    }

    let value = withoutExport.slice(eq + 1).trim();
    const quoted = /^(['"])(.*)\1$/s.exec(value);
    if (quoted) {
      value = quoted[2]!;
    } else {
      // Only strip a trailing comment on unquoted values; a `#` inside quotes is data.
      const hash = value.indexOf(' #');
      if (hash !== -1) {
        value = value.slice(0, hash).trim();
      }
    }

    result[key] = value;
  }

  return result;
}

/**
 * Why this particular key has no route, said in the message rather than left to a doc.
 *
 * Four keys, four different reasons, and an operator hitting one of them is entitled to
 * know which. The old message gave a single sentence for all seventeen — and that
 * sentence, "the application reads it from process.env rather than through
 * ISecretResolver", was untrue of thirteen of them.
 */
function refusalReason(key: string): string {
  switch (key) {
    case 'DB_GRANT_ROLE_URL':
      return (
        'This is a superuser connection string, and @grantjs/database reads it from ' +
        'process.env during a migration — outside the composition root where every ' +
        'other credential is now resolved — so the platform secret would hide it from ' +
        'the migration too. Run `db:grant-rls-role` out of band instead.'
      );
    case 'POSTGRES_PASSWORD':
      return (
        'It already has a safe path: @grantjs/env composes DB_URL from the discrete ' +
        'POSTGRES_* parts, and DB_URL arrives through the platform secret. Deploy with ' +
        '-c dbUrlSecretArn=<arn> and drop the discrete parts.'
      );
    case 'E2E_DB_URL':
    case 'E2E_REDIS_PASSWORD':
      return (
        'This is a test-only key. Nothing outside apps/api/tests reads it, so a ' +
        'deployed stack has no use for it at all — remove the line.'
      );
    default:
      return 'This target has no secure path for it.';
  }
}

/** Splits parsed pairs into what may be synthesized and what may not. */
export function classifyConfig(pairs: Readonly<Record<string, string>>): TargetConfig {
  const env: Record<string, string> = {};
  const secrets: Record<string, string> = {};

  for (const [key, value] of Object.entries(pairs)) {
    if ((STACK_GENERATED_KEYS as readonly string[]).includes(key)) {
      throw new Error(
        `${key} is generated by the stack and cannot be set from the env file. ` +
          'Remove it; CloudFront and the API agree on it without configuration.'
      );
    }

    // An empty value is the template's "unset" state, not an instruction to blank the
    // default. `.env.example` ships every key blank, so treating '' as a value would
    // make copying it a way to silently clear AWS_TARGET_ENV_DEFAULTS.
    if (value === '') {
      continue;
    }

    // After the blank-value skip, so `DB_URL=` in a copied .env.example stays inert,
    // and before the two refusal lists, so the message names the prop that replaces
    // this key rather than the generic "no safe path" sentence below.
    if ((STACK_COMPOSED_KEYS as readonly string[]).includes(key)) {
      throw new Error(
        `${key} cannot be set from this file. With the \`database\` prop the stack ` +
          'composes it from the cluster it creates. To serve against a database this ' +
          'stack did not create, put the URL in Secrets Manager and deploy with ' +
          '-c dbUrlSecretArn=<arn> — the stack renders it as a ' +
          '{{resolve:secretsmanager:...}} dynamic reference inside the platform ' +
          'secret, so the password is present at deploy time and absent from the ' +
          'template. Setting it here would instead make it a Lambda environment ' +
          'variable, in plaintext. See docs/deployment/aws-serverless.md.'
      );
    }

    if ((RESOLVER_SECRET_KEYS as readonly string[]).includes(key)) {
      secrets[key] = value;
      continue;
    }

    // After the resolver check, so the two keys that *do* have a safe path are routed
    // before anything is refused.
    if ((CREDENTIAL_KEYS as readonly string[]).includes(key)) {
      throw new Error(
        `${key} cannot be set from this file. Keys here become Lambda environment ` +
          'variables, which are plaintext in the CloudFormation template, in the ' +
          `function configuration and in cdk.out on disk. ${refusalReason(key)} ` +
          'See docs/deployment/aws-serverless.md § Configure.'
      );
    }

    env[key] = value;
  }

  return { env, secrets };
}

/**
 * Reads and classifies the target's env file. A missing file is not an error — the
 * stack deploys on `AWS_TARGET_ENV_DEFAULTS` alone, which is what every deploy did
 * before this file existed.
 */
export function loadTargetConfig(
  path: string,
  readFile: (p: string) => string,
  exists: (p: string) => boolean
): TargetConfig {
  if (!exists(path)) {
    return { env: {}, secrets: {} };
  }
  return classifyConfig(parseEnvFile(readFile(path)));
}
