import { describe, expect, it } from 'vitest';

import { classifyConfig, loadTargetConfig, parseEnvFile, RESOLVER_SECRET_KEYS } from './env-file';

describe('parseEnvFile', () => {
  it('reads plain pairs and ignores comments and blank lines', () => {
    expect(
      parseEnvFile(['# a comment', '', 'EMAIL_PROVIDER=ses', '  JOBS_PROVIDER=aws  '].join('\n'))
    ).toEqual({ EMAIL_PROVIDER: 'ses', JOBS_PROVIDER: 'aws' });
  });

  it('strips quotes and accepts an export prefix', () => {
    expect(parseEnvFile('export EMAIL_FROM="a@b.com"\nAUTH_MIN_AAL_AT_LOGIN=\'aal2\'')).toEqual({
      EMAIL_FROM: 'a@b.com',
      AUTH_MIN_AAL_AT_LOGIN: 'aal2',
    });
  });

  it('keeps a # that is part of a quoted value', () => {
    // Secrets routinely contain '#'. Truncating one produces a value that is wrong
    // but still looks plausible, which is the worst kind of wrong.
    expect(parseEnvFile('GITHUB_CLIENT_SECRET="abc#def"')).toEqual({
      GITHUB_CLIENT_SECRET: 'abc#def',
    });
  });

  it('drops a trailing comment on an unquoted value', () => {
    expect(parseEnvFile('JOBS_PROVIDER=aws # use EventBridge')).toEqual({ JOBS_PROVIDER: 'aws' });
  });
});

describe('classifyConfig', () => {
  it('routes resolver-backed keys to secrets and everything else to env', () => {
    const { env, secrets } = classifyConfig({
      EMAIL_PROVIDER: 'ses',
      GITHUB_CLIENT_ID: 'public-id',
      GITHUB_CLIENT_SECRET: 'shhh',
      AUTH_MFA_SECRET_ENCRYPTION_KEY: 'also-shhh',
    });

    expect(env).toEqual({ EMAIL_PROVIDER: 'ses', GITHUB_CLIENT_ID: 'public-id' });
    expect(secrets).toEqual({
      GITHUB_CLIENT_SECRET: 'shhh',
      AUTH_MFA_SECRET_ENCRYPTION_KEY: 'also-shhh',
    });
  });

  it.each(RESOLVER_SECRET_KEYS)('never places %s in env', (key) => {
    const { env, secrets } = classifyConfig({ [key]: 'value' });
    expect(env).not.toHaveProperty(key);
    expect(secrets).toHaveProperty(key);
  });

  it('ignores blank values so a copied .env.example changes nothing', () => {
    // Every key in .env.example ships blank. Treating '' as a value would make
    // copying the template a way to silently clear AWS_TARGET_ENV_DEFAULTS.
    expect(classifyConfig({ EMAIL_PROVIDER: '', JOBS_PROVIDER: '' })).toEqual({
      env: {},
      secrets: {},
    });
  });

  it('refuses a stack-generated key rather than ignoring it', () => {
    // Silently dropping it would leave the operator believing they had set the value
    // CloudFront verifies against.
    expect(() => classifyConfig({ ORIGIN_VERIFY_SECRET: 'nope' })).toThrow(
      /generated by the stack/
    );
  });
});

describe('loadTargetConfig', () => {
  it('treats a missing file as no configuration, not an error', () => {
    expect(
      loadTargetConfig(
        '/nonexistent/.env',
        () => {
          throw new Error('should not read');
        },
        () => false
      )
    ).toEqual({ env: {}, secrets: {} });
  });
});
