/**
 * The AWS target's configuration surface.
 *
 * The Helm chart configures a deployment through `values.yaml`; this target uses a
 * `.env` file instead, because the repo already has that surface (`.env`,
 * `.env.example`, `.env.test`, `.env.demo`) and `@grantjs/env` already defines every
 * key. A second format would mean two places to learn and two to drift.
 *
 * Layering, outermost last:
 *
 *   AWS_TARGET_ENV_DEFAULTS  →  the .env file  →  values the stack computes itself
 *
 * The defaults are not replaced by this file: a key the file omits keeps its default.
 *
 * **Secrets do not travel this path.** CloudFormation cannot place a literal secret
 * into a resource without that literal appearing in the template, so keys the
 * application resolves through `ISecretResolver` are split out here and never handed
 * to the stack. They are written to the platform secret out of band instead — which
 * is also the property ADR 0004 bought: a rotation is picked up within the resolver's
 * TTL rather than at the next redeploy.
 */

import type { GrantEnv } from './props';

/**
 * Keys the application reads through `ISecretResolver` rather than `process.env`,
 * and which an operator supplies. Derived from the call sites, not convention:
 * `services/github-oauth.service.ts` and `services/user-mfa.service.ts`.
 *
 * `DB_URL` is resolver-backed too but is not here — the stack computes it from the
 * database it creates, and an operator bringing their own sets it as ordinary `env`.
 */
export const RESOLVER_SECRET_KEYS = [
  'GITHUB_CLIENT_SECRET',
  'AUTH_MFA_SECRET_ENCRYPTION_KEY',
] as const;

/**
 * Generated by the stack and trusted by CloudFront. Supplying it from a file would
 * both put a live secret in the template and break the origin check if it disagreed
 * with what the distribution sends, so it is refused rather than silently ignored.
 */
export const STACK_GENERATED_KEYS = ['ORIGIN_VERIFY_SECRET'] as const;

export interface TargetConfig {
  /** Non-secret keys, destined for the container environment. */
  readonly env: GrantEnv;
  /** Resolver-backed keys, destined for the platform secret out of band. */
  readonly secrets: Readonly<Record<string, string>>;
}

/**
 * Minimal `.env` parser: `KEY=value`, `#` comments, optional `export`, and quoted
 * values. Deliberately not `dotenv` — this reads a file at synth time to build a
 * template, and a parser small enough to read is worth more here than one that also
 * mutates `process.env`.
 */
export function parseEnvFile(contents: string): Record<string, string> {
  const result: Record<string, string> = {};

  for (const rawLine of contents.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) {
      continue;
    }

    const withoutExport = line.startsWith('export ') ? line.slice('export '.length) : line;
    const eq = withoutExport.indexOf('=');
    if (eq <= 0) {
      continue;
    }

    const key = withoutExport.slice(0, eq).trim();
    if (!/^[A-Z_][A-Z0-9_]*$/i.test(key)) {
      continue;
    }

    let value = withoutExport.slice(eq + 1).trim();
    const quoted = /^(['"])(.*)\1$/s.exec(value);
    if (quoted) {
      value = quoted[2]!;
    } else {
      // Only strip a trailing comment on unquoted values; a `#` inside quotes is data.
      const hash = value.indexOf(' #');
      if (hash !== -1) {
        value = value.slice(0, hash).trim();
      }
    }

    result[key] = value;
  }

  return result;
}

/** Splits parsed pairs into what may be synthesized and what may not. */
export function classifyConfig(pairs: Readonly<Record<string, string>>): TargetConfig {
  const env: Record<string, string> = {};
  const secrets: Record<string, string> = {};

  for (const [key, value] of Object.entries(pairs)) {
    if ((STACK_GENERATED_KEYS as readonly string[]).includes(key)) {
      throw new Error(
        `${key} is generated by the stack and cannot be set from the env file. ` +
          'Remove it; CloudFront and the API agree on it without configuration.'
      );
    }

    // An empty value is the template's "unset" state, not an instruction to blank the
    // default. `.env.example` ships every key blank, so treating '' as a value would
    // make copying it a way to silently clear AWS_TARGET_ENV_DEFAULTS.
    if (value === '') {
      continue;
    }

    if ((RESOLVER_SECRET_KEYS as readonly string[]).includes(key)) {
      secrets[key] = value;
    } else {
      env[key] = value;
    }
  }

  return { env, secrets };
}

/**
 * Reads and classifies the target's env file. A missing file is not an error — the
 * stack deploys on `AWS_TARGET_ENV_DEFAULTS` alone, which is what every deploy did
 * before this file existed.
 */
export function loadTargetConfig(
  path: string,
  readFile: (p: string) => string,
  exists: (p: string) => boolean
): TargetConfig {
  if (!exists(path)) {
    return { env: {}, secrets: {} };
  }
  return classifyConfig(parseEnvFile(readFile(path)));
}
