export { assembleExportedSyncProjectInput } from './cdm-export-assemble.lib';
export { validateCdmJsonFields } from './cdm-json.schemas';
export { PermissionCdmEntity } from './entities/permission.cdm-entity';
export { ResourceCdmEntity } from './entities/resource.cdm-entity';
export { RoleTemplateCdmEntity } from './entities/role-template.cdm-entity';
export { TagCdmEntity } from './entities/tag.cdm-entity';
export { UserAssignmentCdmEntity } from './entities/user-assignment.cdm-entity';
export { expandCdmSyncInput } from './expand-cdm-sync-input.lib';
export { refDedupKey, resolveAllPermissionRefs } from './permission-ref.lib';
export type { CdmEntityRegistryDeps } from './registry';
export { createDefaultCdmEntities } from './registry';
