/**
 * Generate TypeScript content for ResourceSlug and ResourceAction from project data.
 * Mirrors the shape of @grantjs/constants permissions/resources.ts.
 */

/** Convert slug (e.g. "user-documents") or action (e.g. "Create") to PascalCase key. */
export function toPascalCase(s: string): string {
  return s
    .split(/[-_:.\s]+/)
    .map((part) => (part.length > 0 ? part[0]!.toUpperCase() + part.slice(1).toLowerCase() : ''))
    .join('');
}

/**
 * Generate the TypeScript file content for ResourceSlug and ResourceAction.
 * - slugs: unique resource slugs from the project (e.g. from GET /api/resources).
 * - actions: unique permission actions from the project (e.g. from GET /api/permissions).
 */
export function generateTypesContent(slugs: string[], actions: string[]): string {
  const slugEntries = [...new Set(slugs)]
    .sort()
    .map((slug) => {
      const key = toPascalCase(slug);
      return key ? `  ${key}: ${JSON.stringify(slug)},` : null;
    })
    .filter(Boolean) as string[];

  const actionEntries = [...new Set(actions)]
    .sort()
    .map((action) => {
      const key = toPascalCase(action);
      return key ? `  ${key}: ${JSON.stringify(action)},` : null;
    })
    .filter(Boolean) as string[];

  const lines = [
    '// Generated by Grant CLI (grant generate-types). Do not edit by hand.',
    '// Project-specific resource slugs and actions for type-safe guards.',
    '',
    '// ResourceSlug: from project resources',
    'export const ResourceSlug = {',
    ...slugEntries,
    '} as const;',
    '',
    'export type ResourceSlug = (typeof ResourceSlug)[keyof typeof ResourceSlug];',
    '',
    '// ResourceAction: unique set from project permissions',
    'export const ResourceAction = {',
    ...actionEntries,
    '} as const;',
    '',
    'export type ResourceAction = (typeof ResourceAction)[keyof typeof ResourceAction];',
    '',
  ];

  return lines.join('\n');
}
